project_name: slack

builds:
  - id: macos
    main: ./cmd/gh-slack
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/rneatherway/gh-slack/internal/version.version={{.Version}}
      - -X github.com/rneatherway/gh-slack/internal/version.commit={{.Commit}}
    env:
      - CGO_ENABLED=1
  - id: other
    main: ./cmd/gh-slack
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -X github.com/rneatherway/gh-slack/internal/version.version={{.Version}}
      - -X github.com/rneatherway/gh-slack/internal/version.commit={{.Commit}}

archives:
  - format: binary
    name_template: "slack-{{.Os}}-{{.Arch}}"
